name: d-cipher
channels:
  - conda-forge
  - defaults
dependencies:
  - cvxopt=1.3.0
  - cvxpy=1.2.1
  - cython=0.29.32
  - jupyter=1.0.0
  - matplotlib=3.6.0
  - mpmath=1.2.1
  - notebook=6.4.12
  - numpy=1.23.3
  - pandas=1.5.0
  - pip=22.2.2
  - python=3.9.13
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - seaborn=0.13.0
  - setuptools=65.3.0
  - sympy=1.10.1
  - tqdm=4.66.1
  - pip:
      - cmake==3.24.1.1
      - derivative==0.4.2
      - pysindy==1.7.1
      - sklearn==0.0
